services:
    message_context.infrastructure.request_handler:
        class: MessageContext\InfrastructureBundle\RequestHandler\Middleware\EventRequestHandler
        arguments:
            - @event_dispatcher
            - @message_context.infrastractrue.guzzle_request_handler

    message_context.infrastractrue.guzzle_request_handler:
        class: MessageContext\InfrastructureBundle\RequestHandler\Middleware\GuzzleRequestHandler
        arguments:
            - @message_context.infrastructure.guzzle_http_client

    message_context.infrastractrue.json_response_listener:
        class: MessageContext\InfrastructureBundle\RequestHandler\Listener\JsonResponseListener
        tags:
            - { name: kernel.event_listener, event: request_handler.received_response, method: onReceivedResponse }


    message_context.infrastructure.guzzle_http_client:
        class: GuzzleHttp\Client
