PostContext\Domain\Message:
    exclusion_policy: ALL
    read_only: false
    access_type: property # defaults to property

    properties:
        messageId:
            expose: true
            access_type: property # defaults to property
            type: string
            serialized_name: message_id
        message:
            expose: true
            access_type: property # defaults to property
            type: string
            serialized_name: message
        channelId:
            expose: true
            inline: true
        publisherId:
            expose: true
            inline: true
