PostContext\Domain\ValueObjects\PublisherId:
    exclusion_policy: ALL
    properties:
        value:
            expose: true
            access_type: property # defaults to property
            serialized_name: publisher_id
